
version: "3.9"
services:
  server1:
    build:
      context: .
    container_name: server1
    command: ["1", "2"]  # server1 starts with the token
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server2,server3
    networks:
      - kv-network
  server2:
    build:
      context: .
    container_name: server2
    command: ["2", "3"]
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server2,server3
    networks:
      - kv-network
  server3:
    build:
      context: .
    container_name: server3
    command: ["3", "1"]
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server2,server3
    networks:
      - kv-network
networks:
  kv-network:
    driver: bridge
