version: "3.9"
services:
  server1:
    build:
      context: .
    container_name: server1
    command: ["1", "2", "true"]  # server1 starts with the token
    environment:
      - CENTRAL_REGISTRY_HOST=server1
    networks:
      - kv-network
  server2:
    depends_on:
        - server1
    build:
      context: .
    container_name: server2
    command: ["2", "3", "false"]
    environment:
      - CENTRAL_REGISTRY_HOST=server1
    networks:
      - kv-network
  # client:
  #   build:
  #     context: ./client  # Build the client image from the "client" directory
  #   container_name: client
  #   environment:
  #     - CENTRAL_REGISTRY_HOST=server1
  #   stdin_open: true       # Keep stdin open to allow user input
  #   tty: true              # Enable an interactive terminal

    

networks:
  kv-network:
    driver: bridge
