
version: "3.9"
services:
  server1:
    build:
      context: .
    restart: always  
    container_name: server1
    command: ["1", "2"]  # server1 starts with the token
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server1,server2,server3,server4,server5
    networks:
      - kv-network
  server2:
    build:
      context: .
    restart: always  
    container_name: server2
    command: ["2", "3"]
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server1,server2,server3,server4,server5
    networks:
      - kv-network
  server3:
    build:
      context: .
    restart: always  
    container_name: server3
    command: ["3", "4"]
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server1,server2,server3,server4,server5
    networks:
      - kv-network
  server4:
    build:
      context: .
    restart: always  
    container_name: server4
    command: ["4", "5"]
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server1,server2,server3,server4,server5
    networks:
      - kv-network
  server5:
    build:
      context: .
    restart: always  
    container_name: server5
    command: ["5", "1"]
    environment:
      - CENTRAL_REGISTRY_HOST=server1
      - PARTICIPANTS=server1,server2,server3,server4,server5
    networks:
      - kv-network
networks:
  kv-network:
    driver: bridge
